// De făcut: creați un export numit a unei funcții numită fib(n)
// exportați funcția fib(n: number) ...

// De făcut: creați un export implicit a unei constante a numărului FibConst
// exportați implicit ...
